name: coffee_cli
version: 0.0.1
description: A sample command-line application.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: any
  ansicolor: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
