name: coffee_cli
version: 0.1.0
description: Easy way to create interactive command line application.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/coffee_cli

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: "^0.13.4+2"
  ansicolor: "^0.0.9"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
