name: coffee_cli
version: 0.3.1
description: Easy way to create interactive command line application.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/coffee_cli

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  worker: "^0.5.0"
  args: "^0.13.4+2"
  ansicolor: "^0.0.9"
  stack_trace: '>=1.3.3 <2.0.0'
  console: "^2.2.3"
  resource: "^1.1.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  testcase: '>=0.1.0 <0.2.0'
